export const ELIGIBLE_POSITIONS=new Set(['QB','RB','TE','WR','FB','K','P']);
export const PLAYER_PROPS=[['passing yards','Pass yds'],['passing touchdowns','Pass TD'],['interceptions','INT'],['rushing yards','Rush yds'],['rushing touchdowns','Rush TD'],['receptions','Receptions'],['receiving yards','Rec yds'],['receiving touchdowns','Rec TD'],['anytime touchdowns','Anytime TD']];
const PROP_TEXT={'passing yards':'pass yds','passing touchdowns':'pass TD','interceptions':'INT','rushing yards':'rush yds','rushing touchdowns':'rush TD','receptions':'receptions','receiving yards':'rec yds','receiving touchdowns':'rec TD','anytime touchdowns':'anytime TD'};
const numberText=v=>{const n=Number(v);return Number.isFinite(n)?String(n):''};
const normalizeProp=raw=>{const prop=String(raw||'').trim().toLowerCase().replace(/\s+/g,' ');if(/^(?:pass|passing)\s+(?:yds?|yards?)$/.test(prop))return 'passing yards';if(/^(?:pass|passing)\s+(?:tds?|touchdowns?)$/.test(prop))return 'passing touchdowns';if(/^(?:ints?|interceptions?)$/.test(prop))return 'interceptions';if(/^(?:rush|rushing)\s+(?:yds?|yards?)$/.test(prop))return 'rushing yards';if(/^(?:rush|rushing)\s+(?:tds?|touchdowns?)$/.test(prop))return 'rushing touchdowns';if(/^(?:receptions?|rec)$/.test(prop))return 'receptions';if(/^(?:rec|receiving)\s+(?:yds?|yards?)$/.test(prop))return 'receiving yards';if(/^(?:rec|receiving)\s+(?:tds?|touchdowns?)$/.test(prop))return 'receiving touchdowns';if(/^(?:anytime\s+)?(?:tds?|touchdowns?)$/.test(prop))return 'anytime touchdowns';return null};
const canonicalProp=prop=>PROP_TEXT[normalizeProp(prop)||String(prop||'').trim().toLowerCase()]||'';
export function buildPlayerPick({player,prop,direction,line}){const p=String(player||'').trim(),stat=normalizeProp(prop),dir=String(direction||'').toLowerCase(),value=numberText(line);return p&&stat&&['over','under'].includes(dir)&&value!==''?`${p} ${dir} ${value} ${PROP_TEXT[stat]}`:''}
export function parsePlayerPick(text){const m=String(text||'').trim().match(/^(.+?)\s+(over|under)\s+(-?(?:\d+(?:\.\d+)?|\.\d+))\s+(.+)$/i);if(!m)return null;const prop=normalizeProp(m[4]);return prop?{player:m[1].trim(),direction:m[2].toLowerCase(),line:Number(m[3]),prop}:null}
export function canonicalizePlayerPick(text){const parsed=parsePlayerPick(text);return parsed?buildPlayerPick(parsed):String(text||'').trim()}
export function compactPlayerPick(text){const parsed=parsePlayerPick(text);if(!parsed)return String(text||'').trim();const parts=parsed.player.split(/\s+/).filter(Boolean),player=parts.length<2?(parts[0]||''):`${/^[A-Z]\.$/i.test(parts[0])?parts[0]:`${parts[0][0]}.`} ${parts.slice(1).join(' ')}`;return `${player} ${parsed.direction} ${numberText(parsed.line)} ${canonicalProp(parsed.prop)}`}
export function buildSinglePick({type,team,opponent,direction,line}){const kind=String(type||''),a=String(team||'').trim(),b=String(opponent||'').trim(),dir=String(direction||'').toLowerCase(),value=numberText(line);if(kind==='moneyline')return a?`${a} moneyline`:'';if(kind==='spread')return a&&value!==''?`${a} ${Number(line)>=0?'+':''}${value} spread`:'';if(kind==='total')return a&&b&&a!==b&&['over','under'].includes(dir)&&value!==''?`${a} vs ${b} ${dir} ${value} total`:'';return ''}
export function parseSinglePick(text){const raw=String(text||'').trim();let m=raw.match(/^(.+?)\s+(?:moneyline|ml|to win)$/i);if(m)return {type:'moneyline',team:m[1].trim(),opponent:'',direction:'',line:''};m=raw.match(/^(.+?)\s+([+-]?\d*\.?\d+)\s+(?:spread|ats)$/i);if(m)return {type:'spread',team:m[1].trim(),opponent:'',direction:'',line:Number(m[2])};m=raw.match(/^(.+?)\s+(?:vs\.?|versus|at)\s+(.+?)\s+(over|under)\s+(\d*\.?\d+)\s+(?:total|game total)$/i);return m?{type:'total',team:m[1].trim(),opponent:m[2].trim(),direction:m[3].toLowerCase(),line:Number(m[4])}:null}
export function normalizeEspnRoster(payload,team){const out=[];for(const group of payload?.athletes||[])for(const athlete of group?.items||[]){const position=athlete?.position?.abbreviation||group?.position?.abbreviation||'';if(!ELIGIBLE_POSITIONS.has(position))continue;const status=String(athlete?.status?.name||athlete?.status?.type||'').toLowerCase();if(status&&status!=='active')continue;const name=athlete?.displayName||athlete?.fullName;if(name)out.push({id:String(athlete.id||name),name,team:team.abbr||team.name,position})}return out}
