export const ELIGIBLE_POSITIONS=new Set(['QB','RB','TE','WR','FB','K','P']);
export const PLAYER_PROPS=[['passing yards','Pass yds'],['passing touchdowns','Pass TD'],['interceptions','INT'],['rushing yards','Rush yds'],['rushing touchdowns','Rush TD'],['receptions','Receptions'],['receiving yards','Rec yds'],['receiving touchdowns','Rec TD'],['anytime touchdowns','Anytime TD']];
export const NFL_TEAMS=[['ARI','Arizona','Cardinals'],['ATL','Atlanta','Falcons'],['BAL','Baltimore','Ravens'],['BUF','Buffalo','Bills'],['CAR','Carolina','Panthers'],['CHI','Chicago','Bears'],['CIN','Cincinnati','Bengals'],['CLE','Cleveland','Browns'],['DAL','Dallas','Cowboys'],['DEN','Denver','Broncos'],['DET','Detroit','Lions'],['GB','Green Bay','Packers'],['HOU','Houston','Texans'],['IND','Indianapolis','Colts'],['JAX','Jacksonville','Jaguars'],['KC','Kansas City','Chiefs'],['LV','Las Vegas','Raiders'],['LAC','Los Angeles','Chargers'],['LAR','Los Angeles','Rams'],['MIA','Miami','Dolphins'],['MIN','Minnesota','Vikings'],['NE','New England','Patriots'],['NO','New Orleans','Saints'],['NYG','New York','Giants'],['NYJ','New York','Jets'],['PHI','Philadelphia','Eagles'],['PIT','Pittsburgh','Steelers'],['SEA','Seattle','Seahawks'],['SF','San Francisco','49ers'],['TB','Tampa Bay','Buccaneers'],['TEN','Tennessee','Titans'],['WSH','Washington','Commanders']].map(([abbr,location,name])=>({abbr,location,name,full:`${location} ${name}`,logoUrl:`https://a.espncdn.com/i/teamlogos/nfl/500/${abbr.toLowerCase()}.png`}));
const PROP_TEXT={'passing yards':'pass yds','passing touchdowns':'pass TD','interceptions':'INT','rushing yards':'rush yds','rushing touchdowns':'rush TD','receptions':'receptions','receiving yards':'rec yds','receiving touchdowns':'rec TD','anytime touchdowns':'anytime TD'};
const numberText=v=>{const n=Number(v);return Number.isFinite(n)?String(n):''};
const normalizeProp=raw=>{const prop=String(raw||'').trim().toLowerCase().replace(/\s+/g,' ');if(/^(?:pass|passing)\s+(?:yds?|yards?)$/.test(prop))return 'passing yards';if(/^(?:pass|passing)\s+(?:tds?|touchdowns?)$/.test(prop))return 'passing touchdowns';if(/^(?:ints?|interceptions?)$/.test(prop))return 'interceptions';if(/^(?:rush|rushing)\s+(?:yds?|yards?)$/.test(prop))return 'rushing yards';if(/^(?:rush|rushing)\s+(?:tds?|touchdowns?)$/.test(prop))return 'rushing touchdowns';if(/^(?:receptions?|rec)$/.test(prop))return 'receptions';if(/^(?:rec|receiving)\s+(?:yds?|yards?)$/.test(prop))return 'receiving yards';if(/^(?:rec|receiving)\s+(?:tds?|touchdowns?)$/.test(prop))return 'receiving touchdowns';if(/^(?:anytime\s+)?(?:tds?|touchdowns?)$/.test(prop))return 'anytime touchdowns';return null};
const canonicalProp=prop=>PROP_TEXT[normalizeProp(prop)||String(prop||'').trim().toLowerCase()]||'';
const cleanTeam=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const teamAliases=team=>[team.abbr,team.location,team.name,team.full];
const normalizeVenue=value=>String(value||'').trim().toLowerCase()==='@'||String(value||'').trim().toLowerCase()==='at'?'@':String(value||'').trim().toLowerCase()==='vs'||String(value||'').trim().toLowerCase()==='versus'?'vs':'';
export function findNflTeam(value){const q=cleanTeam(value);if(!q)return null;const matches=NFL_TEAMS.filter(team=>teamAliases(team).some(alias=>cleanTeam(alias)===q));return matches.length===1?matches[0]:null}
export function teamFullName(value){return findNflTeam(value)?.full||String(value||'').trim()}
export function teamAbbr(value){return findNflTeam(value)?.abbr||String(value||'').trim().toUpperCase()}
export function buildPlayerPick({player,prop,direction,line}){const p=String(player||'').trim(),stat=normalizeProp(prop),dir=String(direction||'').toLowerCase(),value=numberText(line);return p&&stat&&['over','under'].includes(dir)&&value!==''?`${p} ${dir} ${value} ${PROP_TEXT[stat]}`:''}
export function parsePlayerPick(text){const m=String(text||'').trim().match(/^(.+?)\s+(over|under)\s+(-?(?:\d+(?:\.\d+)?|\.\d+))\s+(.+)$/i);if(!m)return null;const prop=normalizeProp(m[4]);return prop?{player:m[1].trim(),direction:m[2].toLowerCase(),line:Number(m[3]),prop}:null}
export function canonicalizePlayerPick(text){const parsed=parsePlayerPick(text);return parsed?buildPlayerPick(parsed):String(text||'').trim()}
export function compactPlayerPick(text){const parsed=parsePlayerPick(text);if(!parsed)return String(text||'').trim();const parts=parsed.player.split(/\s+/).filter(Boolean),player=parts.length<2?(parts[0]||''):`${/^[A-Z]\.$/i.test(parts[0])?parts[0]:`${parts[0][0]}.`} ${parts.slice(1).join(' ')}`;return `${player} ${parsed.direction} ${numberText(parsed.line)} ${canonicalProp(parsed.prop)}`}
export function buildSinglePick({type,team,opponent,direction,line,venue}){const kind=String(type||''),a=teamFullName(team),b=teamFullName(opponent),dir=String(direction||'').toLowerCase(),value=numberText(line),where=normalizeVenue(venue);if(!a||!b||cleanTeam(a)===cleanTeam(b))return '';if(kind==='moneyline')return where?`${a} ${where} ${b} ML`:`${a} to beat ${b}`;if(kind==='spread')return value!==''?(where?`${a} ${Number(line)>=0?'+':''}${value} ${where} ${b} ATS`:`${a} ${Number(line)>=0?'+':''}${value} vs ${b}`):'';if(kind==='total'&&['over','under'].includes(dir)&&value!==''){if(where==='@')return `${a} @ ${b} ${dir} ${value} total`;if(where==='vs')return `${b} @ ${a} ${dir} ${value} total`;return `${a} vs ${b} ${dir} ${value} total`;}return ''}
export function parseSinglePick(text){const raw=String(text||'').trim();let m=raw.match(/^(.+?)\s+(vs|@)\s+(.+?)\s+ML$/i);if(m)return {type:'moneyline',team:teamFullName(m[1]),opponent:teamFullName(m[3]),direction:'',line:'',venue:normalizeVenue(m[2])};m=raw.match(/^(.+?)\s+([+-]?\d*\.?\d+)\s+(vs|@)\s+(.+?)\s+ATS$/i);if(m)return {type:'spread',team:teamFullName(m[1]),opponent:teamFullName(m[4]),direction:'',line:Number(m[2]),venue:normalizeVenue(m[3])};m=raw.match(/^(.+?)\s+to\s+beat\s+(.+)$/i);if(m)return {type:'moneyline',team:teamFullName(m[1]),opponent:teamFullName(m[2]),direction:'',line:'',venue:''};m=raw.match(/^(.+?)\s+(?:to\s+win|moneyline|ml)(?:\s+(vs\.?|versus|at|@)\s+(.+))?$/i);if(m)return {type:'moneyline',team:teamFullName(m[1]),opponent:teamFullName(m[3]||''),direction:'',line:'',venue:normalizeVenue(m[2])};m=raw.match(/^(.+?)\s+([+-]?\d*\.?\d+)\s+(vs\.?|versus|at|@)\s+(.+?)(?:\s+ATS)?$/i);if(m)return {type:'spread',team:teamFullName(m[1]),opponent:teamFullName(m[4]),direction:'',line:Number(m[2]),venue:normalizeVenue(m[3])};m=raw.match(/^(.+?)\s+([+-]?\d*\.?\d+)\s+(?:spread|ats)$/i);if(m)return {type:'spread',team:teamFullName(m[1]),opponent:'',direction:'',line:Number(m[2]),venue:''};m=raw.match(/^(.+?)\s+(vs\.?|versus|at|@)\s+(.+?)\s+(over|under)\s+(\d*\.?\d+)\s+(?:total|game total)$/i);return m?{type:'total',team:teamFullName(m[1]),opponent:teamFullName(m[3]),direction:m[4].toLowerCase(),line:Number(m[5]),venue:normalizeVenue(m[2])}:null}
export function normalizeEspnRoster(payload,team){const out=[];for(const group of payload?.athletes||[])for(const athlete of group?.items||[]){const position=athlete?.position?.abbreviation||group?.position?.abbreviation||'';if(!ELIGIBLE_POSITIONS.has(position))continue;const status=String(athlete?.status?.name||athlete?.status?.type||'').toLowerCase();if(status&&status!=='active')continue;const name=athlete?.displayName||athlete?.fullName;if(name)out.push({id:String(athlete.id||name),name,team:team.abbr||team.name,position})}return out}