export const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((c||0)/100);
function validWeekPlayers(week,scores){const matchups=week.matchups||[];if(matchups.length!==2)return false;const players=matchups.flatMap(m=>[m.player1,m.player2]);if(players.length!==4||new Set(players).size!==4)return false;return players.every(p=>Object.prototype.hasOwnProperty.call(scores,p));}
export function weekResult(week){const scores=week.scores||{};if(!validWeekPlayers(week,scores))return {complete:false,invalid:true,reason:'Week matchups must contain four different scored players.',dues:[],matchups:[]};const players=week.matchups.flatMap(m=>[m.player1,m.player2]),vals=players.filter(p=>scores[p]!==''&&scores[p]!==null&&scores[p]!==undefined&&Number.isFinite(Number(scores[p]))).map(p=>[p,Number(scores[p])]);if(vals.length!==4||vals.every(([,v])=>v===0))return {complete:false,dues:[],matchups:[]};if(week.sleeperScoresSyncedAt&&week.scoresFinal!==true)return {complete:false,live:true,reason:'Sleeper scores are still live.',dues:[],matchups:[]};const sorted=[...vals].sort((a,b)=>a[1]-b[1]);if(sorted[0][1]===sorted[1][1])return {complete:false,tie:true,reason:'Lowest-score tie requires commissioner resolution.',dues:[],matchups:[]};const low=sorted[0][0];let otherLoser=null;const results=[];for(const m of week.matchups){const a=Number(scores[m.player1]),b=Number(scores[m.player2]);if(a===b)return {complete:false,tie:true,reason:'Matchup tie requires commissioner resolution.',dues:[],matchups:[]};const winner=a>b?m.player1:m.player2,loser=a>b?m.player2:m.player1;results.push({...m,winner,loser});if(loser!==low)otherLoser=loser;}if(!otherLoser){const lowMatch=results.find(r=>r.loser===low);otherLoser=results.find(r=>r!==lowMatch)?.loser||null;}if(!otherLoser)return {complete:false,invalid:true,reason:'Could not derive the $5 weekly charge.',dues:[],matchups:[]};return {complete:true,matchups:results,dues:[{player:low,amountCents:1000,reason:'lowest score this week'},{player:otherLoser,amountCents:500,reason:'lost the other matchup'}]};}
export function duesRows(data){const rows=[];for(const w of data.weeks){if(w.type!=='regular')continue;const r=weekResult(w);if(!r.complete)continue;for(const d of r.dues){const key=`${d.player}:${d.amountCents}`;rows.push({week:w.week,...d,paid:Boolean(w.payments?.[key])});}}return rows;}
export function parlayStats(data){return data.players.map(player=>{const legs=data.weeks.flatMap(w=>(w.bets||[]).flatMap(b=>(b.legs||[]).filter(l=>l.player===player&&['hit','miss'].includes(l.status))));const hits=legs.filter(l=>l.status==='hit').length,total=legs.length;return {player,hits,total,pct:total?Math.round(hits/total*100):null};});}
export function playerStats(data){const rows=duesRows(data),gambling=Object.fromEntries(parlayStats(data).map(x=>[x.player,x]));return data.players.map(player=>{const mine=rows.filter(x=>x.player===player);const ten=mine.filter(x=>x.amountCents===1000).length,five=mine.filter(x=>x.amountCents===500).length;const chargedCents=mine.reduce((s,x)=>s+x.amountCents,0),paidCents=mine.filter(x=>x.paid).reduce((s,x)=>s+x.amountCents,0);return {player,tenWeeks:ten,fiveWeeks:five,chargedCents,paidCents,owesCents:chargedCents-paidCents,parlay:gambling[player]};});}
export function duesSummary(data){const stats=playerStats(data);const collectedCents=stats.reduce((s,x)=>s+x.paidCents,0),unpaidCents=stats.reduce((s,x)=>s+x.owesCents,0);return {collectedCents,unpaidCents,chargedCents:collectedCents+unpaidCents};}
export function ledger(data){const rows=[];for(const w of data.weeks){const r=w.type==='regular'?weekResult(w):{complete:false};if(r.complete)for(const d of r.dues){const key=`${d.player}:${d.amountCents}`;if(w.payments?.[key])rows.push({week:w.week,kind:'dues-payment',amountCents:d.amountCents,label:`${d.player} paid — ${d.reason}`});}for(const b of w.bets||[]){const label=b.legs?.length?'$10 parlay':b.description;if(label)rows.push({week:w.week,kind:'stake',amountCents:-Math.abs(b.stakeCents||0),label});if(Number(b.payoutCents)>0)rows.push({week:w.week,kind:'payout',amountCents:Number(b.payoutCents),label:`${label} payout`});}}for(const a of data.adjustments||[]){if(a.kind==='season-bet-placer-adjustment')continue;rows.push({week:a.week??null,season:Boolean(a.season),kind:a.kind||'adjustment',amountCents:Number(a.amountCents)||0,label:a.reason||'Adjustment'});}return rows;}
export function pot(data){return Number(data.season.startingPotCents||0)+ledger(data).reduce((s,r)=>s+r.amountCents,0);}
export function currentWeek(data){const regular=data.weeks.filter(w=>w.type==='regular');return regular.find(w=>!weekResult(w).complete)?.week||data.season.playoffStartWeek;}
