import {loadLeague} from './storage.js?v=20260921-public-bet-results';
import {money,pot,weekResult,ledger,playerStats,duesSummary} from './calculations.js?v=20260921-public-bet-results';
import {liveSleeperWeek,sleeperState} from './sleeper.js?v=20260921-public-bet-results';
import {detectBetResults} from './bet-results.js?v=20260921-public-bet-results';
import {dashboardWeek} from './dashboard-week.js?v=20260921-public-redesign4';

const app=document.querySelector('#app'),sync=document.querySelector('#sync'),seasonContext=document.querySelector('#season-context');
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
const icons={
  week:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 3v3M18 3v3M4 8h16M5 5h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z"/></svg>',
  pot:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.7"><circle cx="8" cy="13" r="5"/><circle cx="15.5" cy="9" r="4.5"/><circle cx="15" cy="16.5" r="4"/><path d="M8 10.8v4.4M6.8 11.7c.7-.7 2.9-.6 2.9.5 0 1.4-3 .7-3 2 0 1.1 2.2 1.2 3 .4" stroke-linecap="round"/></svg>',
  trophy:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M8 4h8v4a4 4 0 0 1-8 0V4Z"/><path d="M8 6H5a2 2 0 0 0 2 4h1M16 6h3a2 2 0 0 1-2 4h-1M12 12v4M9 20h6M10 16h4"/></svg>',
  dice:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r="1" fill="currentColor" stroke="none"/><circle cx="16" cy="8" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="8" cy="16" r="1" fill="currentColor" stroke="none"/><circle cx="16" cy="16" r="1" fill="currentColor" stroke="none"/></svg>',
  dartTarget:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="9.5" cy="14.5" r="6.5"/><circle cx="9.5" cy="14.5" r="3.5"/><circle cx="9.5" cy="14.5" r="1" fill="currentColor" stroke="none"/><path d="M10.2 13.8 18.2 5.8"/><path d="m18.2 5.8-.4-3.3 2 2 2.9-.1-2.4 2.4.2 2.8-2.3-2.3Z"/></svg>'
};
const icon=(name,cls='section-icon')=>`<span class="${cls}" aria-hidden="true">${icons[name]||''}</span>`;
function statusBadge(label,tone='placed'){if(label==='LIVE · SLEEPER')return '<span class="section-status live"><span>LIVE</span><i>·</i><span>SLEEPER</span></span>';return `<span class="section-status ${tone}">${esc(label)}</span>`;}
function averageScores(d){const totals=new Map(d.players.map(p=>[p,{sum:0,count:0}]));for(const w of d.weeks){if(w.type!=='regular'||!weekResult(w).complete)continue;for(const p of d.players){const score=Number(w.scores?.[p]);if(Number.isFinite(score)){const t=totals.get(p);t.sum+=score;t.count++;}}}return Object.fromEntries([...totals].map(([p,t])=>[p,t.count?(t.sum/t.count).toFixed(2):null]));}
function parlaySummary(d,x){const statuses=d.weeks.flatMap(w=>(w.bets||[]).flatMap(b=>(b.legs||[]).filter(l=>l.player===x.player).map(l=>l.status||'pending')));if(!statuses.length)return '<div class="stat-line"><span>Parlay legs</span><b>—</b></div>';const decided=statuses.filter(s=>s==='hit'||s==='miss'),hits=decided.filter(s=>s==='hit').length,losses=decided.filter(s=>s==='miss').length,pct=decided.length?Math.round(hits/decided.length*100):null,recent=statuses.slice(-5);return `<div class="parlay-summary"><div class="parlay-summary-head"><span>Parlay legs</span><b>${decided.length?`${hits}-${losses} (${pct}%)`:'—'}</b></div><div class="parlay-track">${recent.map(s=>`<i class="parlay-dot ${s==='hit'?'hit':s==='miss'?'miss':s==='pending'?'pending':'push'}">${s==='hit'?'✓':s==='miss'?'×':s==='pending'?'○':'–'}</i>`).join('')}</div></div>`;}
function matchupRows(w,r,{showScores=true,averages={}}={}){if(!w?.matchups?.length)return '<p class="muted">Matchups not set yet.</p>';const dues=Object.fromEntries((r?.dues||[]).map(d=>[d.player,d.amountCents]));return w.matchups.map(m=>{const a=w.scores?.[m.player1],b=w.scores?.[m.player2],rr=r?.matchups?.find(x=>x.player1===m.player1&&x.player2===m.player2);const resultClass=p=>rr?.winner===p?'winner':dues[p]===1000?'score-ten':dues[p]===500?'score-five':'';const name=p=>`${rr?.winner===p?icon('trophy','winner-trophy'):''}<b>${esc(p)}</b>`;const avg=p=>`<div class="average">AVG ${esc(averages[p]??'—')}</div>`;const left=showScores?`<div class="score">${a??'—'}</div>`:avg(m.player1),right=showScores?`<div class="score">${b??'—'}</div>`:avg(m.player2);return `<div class="matchup"><div class="team ${resultClass(m.player1)}"><div class="team-name">${name(m.player1)}</div>${left}</div><span class="muted">vs</span><div class="team ${resultClass(m.player2)}"><div class="team-name">${name(m.player2)}</div>${right}</div></div>`}).join('');}
function compactDues(r,extraClass=''){if(!r?.complete||!r.dues?.length)return '';return `<div class="dues compact-dues${extraClass?` ${extraClass}`:''}">${r.dues.map(x=>`<span class="pill ${x.amountCents===1000?'dues-ten':'dues-five'}">${esc(x.player)} · ${money(x.amountCents)}</span>`).join('')}</div>`;}
function renderResultWeek(w){const r=weekResult(w);return `<div class="result-week"><div class="result-week-heading"><h3>Week ${w.week}</h3>${statusBadge('FINAL','final')}</div><div class="matchups">${matchupRows(w,r)}</div>${compactDues(r)}</div>`;}
function detectedLegStatus(leg,detected){if((leg.status||'pending')!=='pending')return null;const match=detected?.legs?.find(x=>x.player===leg.player&&x.pick===leg.pick);return match?.result?.settled?match.result.status:null;}
function detectedSingleStatus(bet,detected){if(bet.status!=='placed'||bet.description!==detected?.single?.description)return null;return detected?.single?.result?.settled?detected.single.result.status:null;}
function betLifecycle(w,detected){const bets=w?.bets||[];if(!bets.length)return null;if(bets.every(b=>b.status!=='placed'))return 'FINAL';const progressed=bets.some(b=>b.legs?.some(l=>['hit','miss','push'].includes(l.status)))||(detected?.legs||[]).some(x=>x.result?.settled)||Boolean(detected?.single?.result?.settled);return progressed?'LIVE':'PLACED';}
function renderBets(w,detected=null){const bets=w?.bets||[];if(!bets.length)return '<p class="muted">No bets recorded for this week.</p>';let hasAuto=false;const html=bets.map(b=>{if(b.legs?.length){const outcome=(b.status||'placed').toLowerCase();return `<div class="bet-card"><div class="bet-head"><div class="bet-title">${icon('dice','bet-icon')}<div class="bet-title-copy"><b>$10 Parlay</b><small class="bet-meta">${esc(b.status)} · ${money(b.stakeCents)}${b.payoutCents?` → ${money(b.payoutCents)}`:''}</small></div></div><span class="bet-outcome ${esc(outcome)}">${esc(b.status)}</span></div><div class="parlay-legs">${b.legs.map(l=>{const auto=detectedLegStatus(l,detected);if(auto)hasAuto=true;const shown=auto||l.status||'pending';return `<div class="parlay-leg"><b>${esc(l.player)}</b><span>${esc(l.pick)}</span><em class="leg-${esc(shown)}">${esc(shown)}${auto?' · auto':''}</em></div>`;}).join('')}</div></div>`;}const auto=detectedSingleStatus(b,detected);if(auto)hasAuto=true;const shown=auto||b.status||'placed';return `<div class="bet-card"><div class="bet-head"><div class="bet-title">${icon('dartTarget','bet-icon')}<div class="bet-title-copy"><b>$5 Bet</b><small>${esc(b.description)}</small></div></div><span class="bet-outcome ${esc(shown)}">${esc(shown)}</span></div><div class="bet"><span class="preserve-lines">${esc(b.description)}</span><span class="bet-meta">${esc(b.status)}${auto?` · auto ${esc(auto)}`:''} · ${money(b.stakeCents)}${b.payoutCents?` → ${money(b.payoutCents)}`:''}</span></div></div>`;}).join('');return `<div class="bets-shell">${html}</div>${hasAuto?'<p class="muted">AUTO results are read-only until the commissioner saves the official status in Admin.</p>':''}`;}
function seasonYear(d){const text=`${d.season?.label||''} ${d.id||''}`;const match=text.match(/\b(20\d{2})\b/);return match?Number(match[1]):null;}
async function publicBetResults(d,w){if(!w?.bets?.length)return null;const parlay=w.bets.find(b=>b.legs?.length),single=w.bets.find(b=>!b.legs?.length&&Number(b.stakeCents)===500);const unresolvedLegs=(parlay?.legs||[]).filter(l=>(l.status||'pending')==='pending'),singleDescription=single?.status==='placed'?single.description:'';if(!unresolvedLegs.length&&!singleDescription)return null;const season=seasonYear(d);if(!season)return null;try{return await detectBetResults({season,week:w.week,parlayLegs:unresolvedLegs,singleDescription});}catch(error){console.warn('Automatic public bet results unavailable; using saved tracker statuses.',error);return null;}}
function matchupLifecycle(w,live){if(live)return 'LIVE · SLEEPER';return weekResult(w).complete?'FINAL':'UPCOMING';}
function render(d,live=null,detected=null){
  const n=dashboardWeek(d),displayWeek=live||d.weeks.find(x=>x.week===n),betWeek=d.weeks.find(x=>x.week===n)||null,rows=ledger(d),stats=playerStats(d),summary=duesSummary(d),balance=pot(d),winner=Math.round(balance*.30),each=Math.round(balance*.20),playoffBankroll=balance-winner-(each*3),averages=averageScores(d),recent=d.weeks.filter(w=>w.type==='regular'&&w.week<n&&weekResult(w).complete).sort((a,b)=>b.week-a.week).slice(0,2);
  if(seasonContext)seasonContext.textContent=`${d.season?.label||'2026–2027'} SEASON | WEEK ${n}`;
  const matchupState=displayWeek&&displayWeek.type!=='betting'?matchupLifecycle(displayWeek,live):null,currentResult=displayWeek&&!live?weekResult(displayWeek):null,showCurrentScores=Boolean(live)||Boolean(currentResult?.complete),betState=betLifecycle(betWeek,detected);
  app.innerHTML=`<section class="summary-board" aria-label="Season summary"><div class="metric metric-week" data-summary="week">${icon('week','metric-icon')}<div><span>Week</span><strong>${n}</strong></div></div><div class="metric metric-pot" data-summary="pot">${icon('pot','metric-icon')}<div><span>Pot</span><strong>${money(balance)}</strong></div></div><div class="summary-secondary"><div class="metric metric-minor" data-summary="collected"><span>Collected</span><strong>${money(summary.collectedCents)}</strong></div><div class="metric metric-minor metric-unpaid" data-summary="unpaid"><span>Unpaid</span><strong>${money(summary.unpaidCents)}</strong></div></div></section>
  <section><p class="eyebrow">Players</p><div class="player-grid">${stats.map(x=>`<div class="player-card"><h2>${esc(x.player)}</h2><div class="stat-line"><span>$10 weeks</span><b>${x.tenWeeks}</b></div><div class="stat-line"><span>$5 weeks</span><b>${x.fiveWeeks}</b></div>${parlaySummary(d,x)}${x.owesCents?`<div class="stat-line owes-line"><span>Owes</span><b class="error">${money(x.owesCents)}</b></div>`:''}</div>`).join('')}</div></section>
  ${displayWeek&&displayWeek.type!=='betting'?`<section class="card matchup-feature"><div class="dashboard-section-head"><div><p class="eyebrow section-main-label">Fantasy matchups</p><h2>Week ${displayWeek.week}${displayWeek.type==='playoff'?' · Playoffs':''}</h2></div><div class="matchup-heading-meta">${statusBadge(matchupState,matchupState==='FINAL'?'final':matchupState.startsWith('LIVE')?'live':'placed')}</div></div><div class="matchups current-matchups">${matchupRows(displayWeek,currentResult,{showScores:showCurrentScores,averages})}</div>${compactDues(currentResult,'current-dues')}</section>`:''}
  <section class="card bets-card"><div class="dashboard-section-head"><p class="eyebrow section-main-label">Bets</p>${betState?statusBadge(betState,betState==='FINAL'?'final':betState==='LIVE'?'live':'placed'):''}</div><div class="bets">${renderBets(betWeek,detected)}</div></section>
  <section class="card payout-card"><p class="eyebrow section-main-label">Season payout</p><div class="payout-row"><span>Playoff champion <small>30%</small></span><strong>${money(winner)}</strong></div><div class="payout-row"><span>Other three players <small>20%</small></span><strong>${money(each)}</strong></div><div class="payout-row"><span>Playoff betting fund <small>10%</small></span><strong>${money(playoffBankroll)}</strong></div><p class="muted payout-note">Projected from the current pot.</p></section>
  <section class="card results-card"><p class="eyebrow section-main-label">Recent matchups</p><div class="recent-results">${recent.length?recent.map(renderResultWeek).join(''):'<p class="muted">No completed prior weeks yet.</p>'}</div></section>
  <section class="card"><p class="eyebrow section-main-label">Pot activity</p><div class="history">${rows.slice(-8).reverse().map(x=>`<div class="history-row"><span>${x.season?'SEASON':`W${x.week??'—'}`} · ${esc(x.label)}</span><b>${x.amountCents>=0?'+':''}${money(x.amountCents)}</b></div>`).join('')||'<p class="muted">No activity yet.</p>'}</div></section>`;
}
function renderUpdated(d){if(d.metadata?.lastUpdated){const updated=new Date(d.metadata.lastUpdated),date=updated.toLocaleDateString(),time=updated.toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'});sync.innerHTML=`<span class="updated-label">UPDATED</span><span class="updated-date">${esc(date)}</span><i class="updated-sep">|</i><span class="updated-time">${esc(time)}</span>`;}else sync.textContent='PRESEASON';}
try{const d=await loadLeague();let live=null;const n=dashboardWeek(d),w=d.weeks.find(x=>x.week===n),betWeek=d.weeks.find(x=>x.week===n);if(w&&w.type!=='betting'&&d.sleeper?.rosterMap){try{const state=await sleeperState();if(Number(state?.week)===Number(n))live=await liveSleeperWeek(d,w);}catch(e){console.warn('Sleeper live scores unavailable; using saved tracker data.',e)}}const detected=await publicBetResults(d,betWeek);render(d,live,detected);renderUpdated(d);}catch(e){app.innerHTML=`<section class="card error">${esc(e.message)}</section>`;sync.textContent='LOAD ERROR';}