export const PLAYERS=['Duncan','Jacob','Matt','Weston'];
const BET_STATUSES=['placed','won','lost','push','void'],LEG_STATUSES=['pending','hit','miss','push'];
const cycle=[[['Duncan','Matt'],['Jacob','Weston']],[['Duncan','Weston'],['Jacob','Matt']],[['Duncan','Jacob'],['Weston','Matt']]];
export function regularSeasonWeeks(){return Array.from({length:14},(_,i)=>({week:i+1,type:'regular',matchups:cycle[i%3].map(([player1,player2])=>({player1,player2})),scores:{},bets:[]}));}
export function initialLeague(){return {schemaVersion:2,id:'buff-husky-2026',season:{name:'Buff Husky Fantasy',label:'2026–2027',status:'active',startingPotCents:0,regularSeasonWeeks:14,playoffStartWeek:15},players:[...PLAYERS],weeks:[...regularSeasonWeeks(),{week:15,type:'playoff',matchups:[],scores:{},bets:[]}],adjustments:[],seasonPayout:{playoffWinner:null,percentages:[30,20,20,20,10]},metadata:{lastUpdated:null}};}
const isInt=n=>Number.isInteger(Number(n));
const validPlayer=p=>PLAYERS.includes(p);
function validateBet(b,week){if(!b||typeof b!=='object')throw new Error(`Week ${week} contains an invalid bet.`);if(!isInt(b.stakeCents)||Number(b.stakeCents)<0)throw new Error(`Week ${week} contains an invalid bet stake.`);if(!BET_STATUSES.includes(b.status))throw new Error(`Week ${week} contains an invalid bet status.`);if(!isInt(b.payoutCents||0)||Number(b.payoutCents||0)<0)throw new Error(`Week ${week} contains an invalid payout.`);if(b.legs!==undefined){if(!Array.isArray(b.legs))throw new Error(`Week ${week} parlay legs must be a list.`);for(const l of b.legs){if(!validPlayer(l?.player)||typeof l.pick!=='string'||!LEG_STATUSES.includes(l.status||'pending'))throw new Error(`Week ${week} contains an invalid parlay leg.`);}}}
export function validateLeague(d){if(!d||d.schemaVersion!==2)throw new Error('Unsupported backup schema.');if(!Array.isArray(d.players)||d.players.length!==PLAYERS.length||new Set(d.players).size!==PLAYERS.length||PLAYERS.some(p=>!d.players.includes(p)))throw new Error('League must contain exactly the four configured players.');if(!d.season||!isInt(d.season.startingPotCents)||Number(d.season.startingPotCents)<0)throw new Error('Invalid season configuration.');if(!Array.isArray(d.weeks)||d.weeks.length<15)throw new Error('Missing league weeks.');const nums=new Set();for(const w of d.weeks){if(!w||!isInt(w.week)||Number(w.week)<1||nums.has(Number(w.week)))throw new Error('Weeks must have unique positive week numbers.');nums.add(Number(w.week));if(!['regular','playoff'].includes(w.type))throw new Error(`Week ${w.week} has an invalid type.`);if(!Array.isArray(w.matchups)||typeof (w.scores||{})!=='object'||!Array.isArray(w.bets||[]))throw new Error(`Week ${w.week} has invalid structure.`);for(const m of w.matchups)if(!validPlayer(m?.player1)||!validPlayer(m?.player2)||m.player1===m.player2)throw new Error(`Week ${w.week} contains an invalid matchup.`);for(const [p,v] of Object.entries(w.scores||{}))if(!validPlayer(p)||(v!==''&&(!Number.isFinite(Number(v))||Number(v)<0)))throw new Error(`Week ${w.week} contains an invalid score.`);for(const b of w.bets||[])validateBet(b,w.week);for(const [key,v] of Object.entries(w.payments||{}))if(typeof key!=='string'||v!==true)throw new Error(`Week ${w.week} contains invalid payment data.`);for(const [p,v] of Object.entries(w.projections||{}))if(!validPlayer(p)||!Number.isFinite(Number(v))||Number(v)<0)throw new Error(`Week ${w.week} contains an invalid projection.`);}if(!Array.isArray(d.adjustments||[]))throw new Error('Adjustments must be a list.');for(const a of d.adjustments||[])if(!a||!isInt(a.amountCents))throw new Error('Invalid pot adjustment.');if(d.betPlacerActualBets!==undefined){if(!d.betPlacerActualBets||typeof d.betPlacerActualBets!=='object'||Array.isArray(d.betPlacerActualBets))throw new Error('Invalid $5 bet adjustment tracking.');for(const [week,cents] of Object.entries(d.betPlacerActualBets))if(!/^\d+$/.test(week)||!isInt(cents)||Number(cents)<0||Number(cents)>500)throw new Error('Invalid $5 bet adjustment amount.');}if(d.metadata?.lastUpdated!==null&&d.metadata?.lastUpdated!==undefined&&Number.isNaN(Date.parse(d.metadata.lastUpdated)))throw new Error('Invalid last-updated timestamp.');return true;}
