export const SLEEPER_LEAGUE_ID='1309539123710693376';
const API='https://api.sleeper.app/v1',PROJECTIONS_API='https://api.sleeper.com';
async function getUrl(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`Sleeper request failed (${r.status}).`);return r.json();}
async function get(path){return getUrl(`${API}${path}`);}
export async function sleeperTeams(){const [league,users,rosters]=await Promise.all([get(`/league/${SLEEPER_LEAGUE_ID}`),get(`/league/${SLEEPER_LEAGUE_ID}/users`),get(`/league/${SLEEPER_LEAGUE_ID}/rosters`)]);const byUser=Object.fromEntries(users.map(u=>[u.user_id,u]));return {league,teams:rosters.map(r=>{const u=byUser[r.owner_id]||{};return {rosterId:r.roster_id,ownerId:r.owner_id,displayName:u.display_name||u.username||`Roster ${r.roster_id}`,teamName:u.metadata?.team_name||''};})};}
export async function sleeperWeek(week){return get(`/league/${SLEEPER_LEAGUE_ID}/matchups/${week}`);}
function projectedPoints(stats={},scoring={}){return Object.entries(scoring).reduce((sum,[key,value])=>sum+(Number(stats[key])||0)*(Number(value)||0),0);}
export async function sleeperUpcoming(data,week,rows=null){if(!data.sleeper?.rosterMap)return null;const [league,matchups]=await Promise.all([get(`/league/${SLEEPER_LEAGUE_ID}`),rows?Promise.resolve(rows):sleeperWeek(week)]);const season=league.season||'2026',seasonType=league.season_type||'regular';const projections=await getUrl(`${PROJECTIONS_API}/projections/nfl/${season}/${week}?season_type=${encodeURIComponent(seasonType)}`);const byPlayer=Object.fromEntries((projections||[]).map(x=>[String(x.player_id),x.stats||{}]));const mapping=data.sleeper.rosterMap,result={};for(const roster of matchups){const player=mapping[String(roster.roster_id)];if(!player)continue;const starters=(roster.starters||[]).filter(id=>id&&id!=='0');if(!starters.length)continue;const total=starters.reduce((sum,id)=>sum+projectedPoints(byPlayer[String(id)]||{},league.scoring_settings||{}),0);if(Number.isFinite(total))result[player]=Number(total.toFixed(2));}return result;}
export async function syncSleeperWeek(data,week){const rows=await sleeperWeek(week.week);importSleeperWeek(data,week,rows);const projections=await sleeperUpcoming(data,week.week,rows);week.projections=projections||{};week.sleeperSyncedAt=new Date().toISOString();return {week,projections:week.projections};}
export function importSleeperWeek(data,week,rows){const mapping=data.sleeper?.rosterMap||{};const mapped=rows.map(x=>({...x,player:mapping[String(x.roster_id)]})).filter(x=>x.player);if(mapped.length!==data.players.length)throw new Error('Map all four Sleeper rosters before syncing scores.');const players=new Set(mapped.map(x=>x.player));if(players.size!==data.players.length)throw new Error('Each Sleeper roster must map to a different tracker player.');if(mapped.some(x=>x.matchup_id==null))throw new Error(`Sleeper Week ${week.week} matchups are not available yet.`);const groups={};for(const x of mapped)(groups[x.matchup_id]??=[]).push(x);const pairs=Object.values(groups);if(pairs.length!==2||pairs.some(g=>g.length!==2))throw new Error('Sleeper did not return two complete matchups for this week.');week.matchups=pairs.map(g=>({player1:g[0].player,player2:g[1].player}));week.scores=Object.fromEntries(mapped.map(x=>[x.player,Number(x.custom_points??x.points)]));return week;}
