import {SUPABASE_URL,SUPABASE_ANON_KEY,LEAGUE_ID,isConfigured} from './config.js?v=20260919-test1';import {initialLeague,validateLeague} from './schema.js?v=20260919-test1';
const headers=()=>({'apikey':SUPABASE_ANON_KEY,'Content-Type':'application/json'});
const ADMIN_URL='https://aduncan450.github.io/fantasy-tracker/admin/';
const SESSION_KEY='bh_session',TEST_MODE_KEY='bh_test_mode',TEST_DATA_KEY='bh_test_data',TEST_SEED_KEY='bh_test_seed';
const REFRESH_EARLY_MS=60*1000;
const clone=x=>JSON.parse(JSON.stringify(x));
const readJson=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const readSession=()=>readJson(SESSION_KEY);
const storeSession=s=>{localStorage.setItem(SESSION_KEY,JSON.stringify(s));return s};
export function isTestMode(){return localStorage.getItem(TEST_MODE_KEY)==='1'}
function readTestData(key=TEST_DATA_KEY){const d=readJson(key);if(!d)throw new Error('Test data is missing. Exit test mode and start again.');validateLeague(d);return d}
function writeTestData(key,data){validateLeague(data);localStorage.setItem(key,JSON.stringify(data));return data}
export async function loadLeague(){if(!isConfigured())return initialLeague();const r=await fetch(`${SUPABASE_URL}/rest/v1/leagues?id=eq.${encodeURIComponent(LEAGUE_ID)}&select=data`,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error('Could not load league data.');const rows=await r.json();if(!rows[0])return initialLeague();validateLeague(rows[0].data);return rows[0].data;}
export async function loadAdminLeague(){return isTestMode()?readTestData():loadLeague()}
export async function saveLeague(data,accessToken){validateLeague(data);if(!isConfigured())throw new Error('Supabase is not configured yet.');data.metadata.lastUpdated=new Date().toISOString();const h=headers();h.Authorization=`Bearer ${accessToken}`;h.Prefer='resolution=merge-duplicates';const r=await fetch(`${SUPABASE_URL}/rest/v1/leagues?on_conflict=id`,{method:'POST',headers:h,body:JSON.stringify({id:LEAGUE_ID,data})});if(!r.ok)throw new Error('Could not save changes. Previous remote data is intact.');return data;}
export async function saveAdminLeague(data,accessToken){validateLeague(data);if(!isTestMode())return saveLeague(data,accessToken);data.metadata=data.metadata||{};data.metadata.lastUpdated=new Date().toISOString();writeTestData(TEST_DATA_KEY,data);return data}
export async function enterTestMode(source='production'){const seed=source==='clean'?initialLeague():await loadLeague();validateLeague(seed);writeTestData(TEST_SEED_KEY,clone(seed));writeTestData(TEST_DATA_KEY,clone(seed));localStorage.setItem(TEST_MODE_KEY,'1');return readTestData()}
export function resetTestMode(){if(!isTestMode())throw new Error('Test mode is not active.');const seed=readTestData(TEST_SEED_KEY);writeTestData(TEST_DATA_KEY,clone(seed));return readTestData()}
export function exitTestMode(){localStorage.removeItem(TEST_MODE_KEY);localStorage.removeItem(TEST_DATA_KEY);localStorage.removeItem(TEST_SEED_KEY)}
export async function signIn(email){if(!isConfigured())throw new Error('Supabase is not configured yet.');const endpoint=`${SUPABASE_URL}/auth/v1/otp?redirect_to=${encodeURIComponent(ADMIN_URL)}`;const r=await fetch(endpoint,{method:'POST',headers:headers(),body:JSON.stringify({email,should_create_user:false,gotrue_meta_security:{captcha_token:null}})});if(!r.ok){let detail='';try{const body=await r.json();detail=body.msg||body.message||body.error_description||body.error||''}catch{}throw new Error(detail?`Could not send sign-in link: ${detail}`:'Could not send sign-in link.');}}
async function refreshSession(s){if(!s?.refresh_token)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:headers(),body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok){localStorage.removeItem(SESSION_KEY);return null}const body=await r.json();if(!body.access_token){localStorage.removeItem(SESSION_KEY);return null}return storeSession({access_token:body.access_token,refresh_token:body.refresh_token||s.refresh_token,expires_at:Date.now()+Number(body.expires_in||3600)*1000});}
export async function session(){const s=readSession();if(!s?.access_token)return null;if(!s.expires_at||Date.now()<s.expires_at-REFRESH_EARLY_MS)return s;return refreshSession(s)}
export async function captureSessionFromHash(){const hash=new URLSearchParams(location.hash.slice(1));const query=new URLSearchParams(location.search);const token=hash.get('access_token')||query.get('access_token');if(token){const expiresIn=Number(hash.get('expires_in')||query.get('expires_in')||3600);const s=storeSession({access_token:token,refresh_token:hash.get('refresh_token')||query.get('refresh_token')||null,expires_at:Date.now()+expiresIn*1000});history.replaceState(null,'',location.pathname);return s}return session();}
export function signOut(){localStorage.removeItem(SESSION_KEY)}
